// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPb42Jtjefiqm-Zo399yunIsTxLXAkams',
    appId: '1:560822888120:web:783219414a4fc4120b764d',
    messagingSenderId: '560822888120',
    projectId: 'amoun-5a154',
    authDomain: 'amoun-5a154.firebaseapp.com',
    storageBucket: 'amoun-5a154.firebasestorage.app',
    measurementId: 'G-SQ0B3R4H58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpKRSALpx_tU41n2mh7Cfgjz_6Sw1BojE',
    appId: '1:560822888120:android:234c4b260c62285d0b764d',
    messagingSenderId: '560822888120',
    projectId: 'amoun-5a154',
    storageBucket: 'amoun-5a154.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJ7AIOYq6y0fmBIKG8J69MnIsZbRCQ0Q',
    appId: '1:560822888120:ios:e9f84092900741070b764d',
    messagingSenderId: '560822888120',
    projectId: 'amoun-5a154',
    storageBucket: 'amoun-5a154.firebasestorage.app',
    iosBundleId: 'com.example.amoun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJ7AIOYq6y0fmBIKG8J69MnIsZbRCQ0Q',
    appId: '1:560822888120:ios:e9f84092900741070b764d',
    messagingSenderId: '560822888120',
    projectId: 'amoun-5a154',
    storageBucket: 'amoun-5a154.firebasestorage.app',
    iosBundleId: 'com.example.amoun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPb42Jtjefiqm-Zo399yunIsTxLXAkams',
    appId: '1:560822888120:web:c3badf98476d431f0b764d',
    messagingSenderId: '560822888120',
    projectId: 'amoun-5a154',
    authDomain: 'amoun-5a154.firebaseapp.com',
    storageBucket: 'amoun-5a154.firebasestorage.app',
    measurementId: 'G-WSG71Q7FXP',
  );
}
